data_file <-read.table("household_power_consumption.txt", sep = ";", header = TRUE)
data_oper <-subset(data_file, Date %in% c("1/2/2007", "2/2/2007"))
data_oper[,1]<-sub("1/2/2007","01/02/2007", data_oper[,1])
data_oper[,1]<-sub("2/2/2007","02/02/2007", data_oper[,1])
data_oper[,10]<-paste(as.character(data_oper[,1]), as.character(data_oper[,2]))
data_oper <-transform(data_oper, V10 = as.POSIXct(V10, format = "%d/%m/%Y %H:%M:%S"))
png("Plot4.png")
par(mfrow = c(2,2))
plot(data_oper[,10], as.numeric(as.character(data_oper[,3])),type="l", ylab="Global Active Power (kilowatts)", xlab= "")
plot(data_oper[,10], as.numeric(as.character(data_oper[,5])), type = "l", ylab ="Voltage",xlab= "datetime")
plot(data_oper[,10], as.numeric(as.character(data_oper[,7])), type = "n",ylab= "Energy sub metering",xlab="")
lines(data_oper[,10], as.numeric(as.character(data_oper[,7])), col = "black")
lines(data_oper[,10], as.numeric(as.character(data_oper[,8])), col = "red")
lines(data_oper[,10], as.numeric(as.character(data_oper[,9])), col = "blue")
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), bty="n",col=c("black","red","blue"),lty=c(1,1,1))
plot(data_oper[,10], as.numeric(as.character(data_oper[,4])),type="l", ylab= "Global_reactive_power", xlab= "datetime")
dev.off()